apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dotnetapp
  template:
    metadata:
      labels:
        name: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: dareyregistry/menzies
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
  strategy:
    type: Recreate
