apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-service
spec:
  selector:
    app: clarity-cloud
    name: clarity-cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
