apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-cluster-operators
spec:
  project: default
  source:
    repoURL: 'https://github.com/darey-io/kafka.git'
    path: strimzi-cluster-operator
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: true
